name: Build Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true
        type: string
        default: "vx.x.x"

jobs:
  builds:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.25.1"

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: false

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Build
        env:
          NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cd internal/webui
          npm install
          npm run build
          cd ../..
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build --ldflags="-s -w" -o bin/lien_linux_amd64 cmd/server/main.go
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build --ldflags="-s -w" -o bin/lien_windows_amd64.exe cmd/server/main.go
          CC="$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang" CXX="$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang++" CGO_ENABLED=1 GOOS=android GOARCH=arm64 go build --ldflags="-s -w" -o bin/lien_android_arm64 cmd/server/main.go

      - name: Save Artifact
        uses: actions/upload-artifact@v6
        with:
          name: files
          path: |
            bin/lien_linux_amd64
            bin/lien_windows_amd64.exe
            bin/lien_android_arm64

  release:
    name: Release
    runs-on: ubuntu-ubuntu-24.04
    needs:
      - builds
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          name: files
          path: files

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          draft: true
          prerelease: true
          files: |
            files/lien_linux_amd64
            files/lien_windows_amd64.exe
            files/lien_android_arm64
